# Generated by Django 4.2.18 on 2025-03-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('PL', 'Planning'), ('OG', 'Ongoing'), ('CO', 'Completed'), ('SU', 'Suspended')], default='PL', max_length=2, verbose_name='Project Status')),
                ('project_document', models.FileField(blank=True, upload_to='project_docs/', verbose_name='Project Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user_auth.organizationprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
