# Generated by Django 4.2.18 on 2025-03-02 14:00

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('PLAN', 'Planning'), ('ONGO', 'Ongoing'), ('COMP', 'Completed'), ('SUSP', 'Suspended')], default='PLAN', max_length=4, verbose_name='Project Status')),
                ('funding_type', models.CharField(choices=[('GRANT', 'Grant'), ('DON', 'Donation'), ('SELF', 'Self-Funded'), ('PART', 'Partnership')], default='GRANT', max_length=5, verbose_name='Funding Type')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Project Budget (TZS)')),
                ('target_regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DAR', 'Dar es Salaam'), ('DSM', 'Dodoma'), ('ARU', 'Arusha'), ('MBY', 'Mbeya'), ('MWA', 'Mwanza'), ('ZNZ', 'Zanzibar'), ('KIG', 'Kigoma'), ('TAN', 'Tanga')], max_length=3), blank=True, default=list, size=None, verbose_name='Target Regions')),
                ('beneficiaries', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Beneficiaries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='organizatio_status_528044_idx'), models.Index(fields=['organization'], name='organizatio_organiz_033792_idx')],
            },
        ),
    ]
