# Generated by Django 4.2 on 2025-03-04 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'First Quarter (Jan-Mar)'), ('Q2', 'Second Quarter (Apr-Jun)'), ('Q3', 'Third Quarter (Jul-Sep)'), ('Q4', 'Fourth Quarter (Oct-Dec)')], max_length=2, verbose_name='Quarter')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('women_reached', models.PositiveIntegerField(default=0, verbose_name='Women Reached')),
                ('men_reached', models.PositiveIntegerField(default=0, verbose_name='Men Reached')),
                ('youth_reached', models.PositiveIntegerField(default=0, verbose_name='Youth Reached (18-35)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='reports', to='organization.project', verbose_name='Projects in this quarter')),
            ],
            options={
                'verbose_name': 'Organization Report',
                'verbose_name_plural': 'Organization Reports',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('organization', 'quarter', 'year')},
            },
        ),
    ]
