# Generated by Django 4.2 on 2025-03-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('organization', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user_auth.organizationprofile'),
        ),
    ]
