# Generated by Django 4.2 on 2025-03-04 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_alter_report_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-year', '-quarter']},
        ),
        migrations.AlterField(
            model_name='report',
            name='men_reached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='projects',
            field=models.ManyToManyField(related_name='reports', to='organization.project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='quarter',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Q1 - January to March'), (2, 'Q2 - April to June'), (3, 'Q3 - July to September'), (4, 'Q4 - October to December')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='women_reached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='youth_reached',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
