# Generated by Django 4.2 on 2025-03-01 09:41

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Official registration number from NGO Coordination Board', max_length=20, unique=True, verbose_name='NGO Registration Number')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+255\\d{9}$')], verbose_name='Phone Number')),
                ('regions_of_operation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DAR', 'Dar es Salaam'), ('DSM', 'Dodoma'), ('ARU', 'Arusha'), ('MBY', 'Mbeya'), ('MWA', 'Mwanza'), ('ZNZ', 'Zanzibar'), ('KIG', 'Kigoma'), ('TAN', 'Tanga')], max_length=3), size=None, verbose_name='Regions of Operation')),
                ('compliance_status', models.CharField(choices=[('C', 'Fully Compliant'), ('P', 'Pending Review'), ('N', 'Non-Compliant'), ('S', 'Suspended')], default='P', max_length=1, verbose_name='Compliance Status')),
                ('registration_certificate', models.FileField(blank=True, upload_to='ngo_docs/', verbose_name='Registration Certificate')),
                ('is_verified', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Budget (TZS)')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('date_established', models.DateField(blank=True, null=True, verbose_name='Date Established')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
